on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest
    name: Run spec
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Test with RSpec
        run: bundle exec rspec

      - name: Upload coverage reports
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage/coverage.xml
          flags: unittests # optional
          name: check-members-for-codecov # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
